function Permutation_310(Ind_No)
% FAST PERMUTATION - 快速分子置换 (含呼吸晶格)
% 对于分子晶体，置换就是交换同类型分子的质心位置
% 置换前先呼吸晶格（放大5-15%），给分子交换留出空间
% GULP 弛豫会自动回到正常距离，不影响最终结果

global POP_STRUC
global ORG_STRUC
global OFF_STRUC

goodMutant = 0;
goodMutLattice = 0;
count = 1;
maxAttempts = 50;  % 从50降到15

while goodMutant + goodMutLattice ~= 2
    count = count + 1;
    if count > maxAttempts
       disp('failed to do permutation in 50 attempts, switch to Random');
       USPEXmessage(511,'',0);
       Random_310(Ind_No);
       break;
    end

    toPerMutate = find (ORG_STRUC.tournament>RandInt(1,1,[0,max(ORG_STRUC.tournament)-1]));
    Ind_P = POP_STRUC.ranking(toPerMutate(end));

    MtypeLIST = POP_STRUC.POPULATION(Ind_P).MtypeLIST;
    numMols   = POP_STRUC.POPULATION(Ind_P).numMols;
    numIons   = POP_STRUC.POPULATION(Ind_P).numIons;
    typesAList= POP_STRUC.POPULATION(Ind_P).typesAList;
    MUT_LAT   = POP_STRUC.POPULATION(Ind_P).LATTICE;

    % ============================================================
    % 呼吸晶格：置换前放大晶格 5-15%，给分子交换留出空间
    % 同时缩放分子坐标，保持分数坐标不变
    % 参考 Rotation_310.m 第38-45行 的相同策略
    % ============================================================
    breathFactor = 1.05 + rand * 0.20;  % 1.05 ~ 1.25
    MUT_LAT_breath = MUT_LAT * breathFactor;

    % 创建父代分子的缩放副本（不修改原父代结构）
    breathMOLS = POP_STRUC.POPULATION(Ind_P).MOLECULES;
    for ind = 1:sum(numMols)
        breathMOLS(ind).MOLCOORS = breathMOLS(ind).MOLCOORS * breathFactor;
        breathMOLS(ind).ZMATRIX(1,:) = breathMOLS(ind).ZMATRIX(1,:) * breathFactor;
    end

    for i = 1:sum(numMols)
        order(i)= breathMOLS(i).order;
    end

    if sum(numMols>0)<2 
       goodMutLattice = 0;
    else
       goodMutLattice = 1;
    end
    
    if goodMutLattice
       for ind = 1:sum(numMols)
           father(ind,:) = breathMOLS(ind).ZMATRIX(1,:);
       end
       
       [PERMUT, noOfSwapsNow] = swapIons_mutation_final(father, numMols, order);
       
       if noOfSwapsNow > 0
          absMUT_COORD= PERMUT*MUT_LAT_breath;

          for ind = 1:sum (numMols)
              displacement(ind,:)=absMUT_COORD(ind,:)-breathMOLS(ind).ZMATRIX(1,:);
          end
          tempMOLS = breathMOLS;
          
          for ind = 1:sum (numMols)
              for inder = 1:3
                  tempMOLS(ind).MOLCOORS(:,inder) = tempMOLS(ind).MOLCOORS(:,inder) +displacement(ind,inder);
              end
          end
          
          % 快速距离检查：使用呼吸后的晶格，更容易通过
          goodMutant = newMolCheck(tempMOLS, MUT_LAT_breath, MtypeLIST, ORG_STRUC.minDistMatrice);
       end
       
       if goodMutant+ goodMutLattice == 2
          for inder = 1: sum(numMols)
              tempMOLS(inder).ZMATRIX = real(NEW_coord2Zmatrix(tempMOLS(inder).MOLCOORS,ORG_STRUC.STDMOL(MtypeLIST(inder)).format));
          end
          OFF_STRUC.POPULATION(Ind_No).MOLECULES = tempMOLS;
          OFF_STRUC.POPULATION(Ind_No).LATTICE =  MUT_LAT_breath;
          OFF_STRUC.POPULATION(Ind_No).numIons =  numIons;
          OFF_STRUC.POPULATION(Ind_No).numMols =  numMols;
          OFF_STRUC.POPULATION(Ind_No).MtypeLIST = MtypeLIST;
          OFF_STRUC.POPULATION(Ind_No).typesAList = typesAList;
          info_parents = struct('parent', {},'noOfSwapsNow', {}, 'enthalpy', {});
          info_parents(1).parent=num2str(POP_STRUC.POPULATION(Ind_P).Number);
          info_parents.noOfSwapsNow=noOfSwapsNow;
          info_parents.enthalpy=POP_STRUC.POPULATION(Ind_P).Enthalpies(end)/sum(numIons);
          OFF_STRUC.POPULATION(Ind_No).Parents = info_parents;
          OFF_STRUC.POPULATION(Ind_No).howCome = ' Permutate ';
          disp(['Structure ' num2str(Ind_No) '  generated by permutation']);
       end 
    end
end
end
