function Rotation_310(Ind_No)
% SMART ROTATION - 改进的旋转变异算法
% 解决 RotInertia 死循环、过度旋转、验证失败率高的问题

global POP_STRUC
global ORG_STRUC
global OFF_STRUC

% === 参数配置 ===
maxAttempts = 50;           % 减少最大尝试次数（原50→25）
maxDihedralIter = 200;      % RotInertia 二面角循环上限
rotationAngleMax = pi/2;    % 最大旋转角从 π/2 降到 π/6 (30°)
translationMax = 0.5;       % 最大平移从 0.5 降到 0.3 Å

goodMutant = 0;
count = 1;

while goodMutant ~= 1
    count = count + 1;
    if count > maxAttempts
        disp('failed to do Smart Rotation, switch to Random');
        Random_310(Ind_No);
        break;
    end
    
    % === 选择父代 ===
    toRotate = find(ORG_STRUC.tournament > RandInt(1,1,[0,max(ORG_STRUC.tournament)-1]));
    IND = POP_STRUC.ranking(toRotate(end));
    
    MtypeLIST = POP_STRUC.POPULATION(IND).MtypeLIST;
    numMols   = POP_STRUC.POPULATION(IND).numMols;
    lattice   = POP_STRUC.POPULATION(IND).LATTICE;
    numIons   = POP_STRUC.POPULATION(IND).numIons;
    typesAList= POP_STRUC.POPULATION(IND).typesAList;
    ROTMOLS   = POP_STRUC.POPULATION(IND).MOLECULES;
    
    % === 旋转前拉开分子间距（呼吸晶格） ===
    % 放大晶格 5-10%，给分子旋转留出空间
    % GULP 弛豫会自动回到正常距离，不影响最终结果
    breathFactor = 1.05 + rand * 0.1;  % 1.05 ~ 1.10
    breathLattice = lattice * breathFactor;
    % 分子质心按比例缩放（保持分数坐标不变）
    for i = 1:sum(numMols)
        ROTMOLS(i).MOLCOORS = ROTMOLS(i).MOLCOORS * breathFactor;
    end
    
    % === 智能旋转 ===
    if isfield(ROTMOLS, 'Operation')
        [ROTMOLS, rotNow] = SmartRotation_Symmetry(ROTMOLS, lattice, MtypeLIST, ...
            rotationAngleMax, translationMax, maxDihedralIter);
    else
        [ROTMOLS, rotNow] = SmartRotation_Random(ROTMOLS, MtypeLIST, ...
            rotationAngleMax, translationMax, maxDihedralIter);
    end
    
    % === 分级验证 ===
    % 第1级: 快速预检查（只检查旋转过的分子周围）
    %if rotNow > 0
    %    quickCheck = quickMolCheck(ROTMOLS, breathLattice, MtypeLIST, ORG_STRUC.minDistMatrice-0.2);
    %else
    %    quickCheck = 0;
    %end
    
    %if quickCheck
        % 第2级: 标准验证（自适应容差）
    %    tolerance = ORG_STRUC.minDistMatrice - 0.2;
    %    if count > 10
    %        tolerance = tolerance - 0.05;  % 后期收紧
    %    end
    %    goodMutant = quickMolCheck(ROTMOLS, breathLattice, MtypeLIST, tolerance);
    %end
    goodMutant =  newMolCheck(ROTMOLS, breathLattice, MtypeLIST, ORG_STRUC.minDistMatrice-0.2);
    % === 保存结果 ===
    if goodMutant == 1
        OFF_STRUC.POPULATION(Ind_No).MOLECULES = ROTMOLS;
        OFF_STRUC.POPULATION(Ind_No).LATTICE = breathLattice;
        OFF_STRUC.POPULATION(Ind_No).numIons = numIons;
        OFF_STRUC.POPULATION(Ind_No).numMols = numMols;
        OFF_STRUC.POPULATION(Ind_No).MtypeLIST = MtypeLIST;
        OFF_STRUC.POPULATION(Ind_No).typesAList = typesAList;
        
        info_parents = struct('parent', {}, 'howManyRots', {}, 'enthalpy',{});
        info_parents(1).parent = num2str(POP_STRUC.POPULATION(IND).Number);
        info_parents.enthalpy = POP_STRUC.POPULATION(IND).Enthalpies(end)/sum(numIons);
        info_parents.howManyRots = rotNow;
        
        OFF_STRUC.POPULATION(Ind_No).Parents = info_parents;
        OFF_STRUC.POPULATION(Ind_No).howCome = 'Rotate';
        disp(['Structure ' num2str(Ind_No) '  generated by smart rotmutation (attempt ' num2str(count) ')']);
    end
end
end

% ============================================================
function [Son, rotNow] = SmartRotation_Symmetry(father, lat, MtypeLIST, angleMax, transMax, maxIter)
% 改进的对称旋转
global ORG_STRUC
STDMOL = ORG_STRUC.STDMOL;
numMols = length(father);
lat_6 = latConverter(lat);
rotNow = numMols;

% 修复: 正确处理空 Operation 的情况
N_Wycc = 0;
Sym = [];
count = 0;

for i = 1:numMols
    if ~isempty(father(i).Operation)
        if isequal(father(i).Operation, [1 0 0; 0 1 0; 0 0 1; 0 0 0])
            N_Wycc = N_Wycc + 1;
            Sym(N_Wycc) = 1;
        else
            if N_Wycc > 0
                Sym(N_Wycc) = Sym(N_Wycc) + 1;
            end
        end
    end
end

Son = father;

for i = 1:N_Wycc
    count = count + 1;
    if count > numMols, break; end
    
    Coords = father(count).MOLCOORS;
    format = STDMOL(MtypeLIST(count)).format;
    num_optFlags = STDMOL(MtypeLIST(count)).num_optFlags;
    
    % 使用 Cython 加速的 RotInertia
    [Zmatrix, REF_MOLCOORS] = fast_SmartRotInertia(Coords, format, num_optFlags, ...
        MtypeLIST(count), angleMax, transMax, maxIter);
    
    for j = 1:Sym(i)
        idx = count + j - 1;
        if idx > numMols, break; end
        R = Operate_molecule(REF_MOLCOORS, Son(idx).Operation, lat_6, [1 2 3], [1 2 3]);
        Son(idx).MOLCOORS = R;
        Son(idx).ZMATRIX = NEW_coord2Zmatrix(R, format);
    end
    count = count + Sym(i) - 1;
end
end

% ============================================================
function [goodSon, rotNow] = SmartRotation_Random(father, MtypeLIST, angleMax, transMax, maxIter)
% 改进的随机旋转: 智能选择旋转对象
% 混合两种旋转策略:
%   - Euler 角旋转 (MAGUS 风格): 全随机 Z-X-Z Euler 角，完整 SO(3) 覆盖
%   - 惯量主轴旋转 (USPEX 原版): 物理意义明确，对细长分子效果好
% 逐分子独立概率旋转 (MAGUS 风格): 每个分子独立决定是否旋转
global ORG_STRUC
STDMOL = ORG_STRUC.STDMOL;
numMols = length(father);

% === 可配置参数 ===
% eulerProb: 使用 Euler 角旋转的概率 (0~1)
%   - 1.0: 纯 MAGUS 风格，全随机 Euler 角
%   - 0.5: 混合策略 (默认)
%   - 0.0: 纯 USPEX 原版，惯量主轴旋转
eulerProb = 0.5;

% rotProb: 每个分子独立被旋转的概率 (MAGUS 风格)
%   - 每个分子独立抛硬币决定是否旋转，而非固定比例
%   - 实际旋转数 ≈ numMols * rotProb，但有随机波动
%   - 0.3: 默认，与原 20-40% 范围的中心值一致
rotProb = 0.3;

goodSon = father;
rotNow = 0;

% 逐分子独立概率旋转 (MAGUS 风格)
for molRot = 1:numMols
    if rand >= rotProb
        continue;  % 该分子不旋转
    end
    
    Coords = father(molRot).MOLCOORS;
    num_optFlags = STDMOL(MtypeLIST(molRot)).num_optFlags;
    
    if size(Coords, 1) > 1
        % 20% 概率做中心反演
        if rand > 0.8
            Coords = bsxfun(@minus, 2*mean(Coords), Coords);
        end
        
        format = STDMOL(MtypeLIST(molRot)).format;
        
        if rand < eulerProb
            % === MAGUS 风格: 全随机 Euler 角旋转 ===
            % 绕分子质心做 Z-X-Z Euler 旋转
            % phi, theta, psi 均匀分布于 [0, 2π]
            % 覆盖完整 SO(3) 旋转群，对球形分子 (如 CL20) 效果更好
            MOLCOORS = rotateMoleculeEuler(Coords);
            
            % 小随机平移 (MAGUS 不做，但保留以增加多样性)
            MOLCOORS = bsxfun(@plus, MOLCOORS, (rand(1,3) - 0.5) * 2 * transMax);
            
            Zmatrix = NEW_coord2Zmatrix(MOLCOORS, format);
        else
            % === USPEX 原版: 惯量主轴旋转 + 二面角优化 ===
            [Zmatrix, MOLCOORS] = fast_SmartRotInertia(Coords, format, num_optFlags, ...
                MtypeLIST(molRot), angleMax, transMax, maxIter);
        end
        
        goodSon(molRot).ZMATRIX = Zmatrix;
        goodSon(molRot).MOLCOORS = MOLCOORS;
        rotNow = rotNow + 1;
    end
end
end

% ============================================================
function [Zmatrix, MOLCOORS] = SmartRotInertia(coords, format, num_optFlags, molRot, angleMax, transMax, maxIter)
% 改进的惯量主轴旋转: 解决死循环问题
global ORG_STRUC
STDMOL = ORG_STRUC.STDMOL;
MOLCOORS = coords;

% 1. 计算惯量主轴
[a, b] = PrincipleAxis(coords);

% 2. 确定参考转动惯量
if abs(b(1,1)) < 0.0001
    Ref = b(2,2);
else
    Ref = b(1,1);
end

% 3. 绕各主轴旋转（使用更小的角度）
for loop = 1:3
    if b(loop, loop) > 0.0001
        % 角度范围从 ±π/2 降到 ±angleMax
        angle = (rand - 0.5) * 2 * angleMax * Ref / b(loop, loop);
        MOLCOORS = Rotate_rigid_body(mean(MOLCOORS), a(:,loop)', MOLCOORS, angle);
    end
end

% 4. 更小的随机平移
MOLCOORS = bsxfun(@plus, MOLCOORS, (rand(1,3) - 0.5) * 2 * transMax);

% 5. 转回 Z-matrix
Zmatrix = NEW_coord2Zmatrix(MOLCOORS, format);

% 6. 柔性二面角处理 — 加上迭代上限！
if num_optFlags > 0
    goodRot = 0;
    iter = 0;
    
    for i = 1:size(coords, 1)
        radiu(i) = str2num(covalentRadius(ORG_STRUC.atomType(STDMOL(molRot).types(i))));
    end
    
    while ~goodRot && iter < maxIter    % ← 关键改进: 加上上限
        iter = iter + 1;
        
        for ind = 1:num_optFlags
            i1 = STDMOL(molRot).flex_dihedral(ind, 1);
            i2 = STDMOL(molRot).flex_dihedral(ind, 2);
            % 渐进式角度: 前期大角度探索，后期小角度微调
            if iter < maxIter/3
                angleStep = (rand - 0.5) * pi;        % 前期: ±90°
            elseif iter < 2*maxIter/3
                angleStep = (rand - 0.5) * pi/3;      % 中期: ±60°
            else
                angleStep = (rand - 0.5) * pi/6;      % 后期: ±30°
            end
            Zmatrix(i1, i2) = Zmatrix(i1, i2) + angleStep;
        end
        
        MOLCOORS = NEW_ZMATRIXCOORD(Zmatrix, format);
        Zmatrix  = NEW_coord2Zmatrix(MOLCOORS, format);
        CN = find_pair(MOLCOORS, radiu);
        
        if isequal(CN, STDMOL(molRot).CN)
            goodRot = 1;
        end
    end
    
    % 如果达到上限仍未成功，使用原始坐标（放弃二面角旋转）
    if ~goodRot
        MOLCOORS = coords;
        % 只保留主轴旋转 + 平移的效果，重新计算
        for loop = 1:3
            if b(loop, loop) > 0.0001
                angle = (rand - 0.5) * 2 * angleMax * Ref / b(loop, loop);
                MOLCOORS = Rotate_rigid_body(mean(MOLCOORS), a(:,loop)', MOLCOORS, angle);
            end
        end
        MOLCOORS = bsxfun(@plus, MOLCOORS, (rand(1,3) - 0.5) * 2 * transMax);
        Zmatrix = NEW_coord2Zmatrix(MOLCOORS, format);
    end
end
end

% ============================================================
function MOLCOORS = rotateMoleculeEuler(MOLCOORS, phi, theta, psi)
% MAGUS 风格的全随机 Euler 角旋转 (Z-X-Z 约定)
% 绕分子质心旋转，覆盖完整 SO(3) 旋转群
% 输入:
%   MOLCOORS — 分子坐标 (m×3)
%   phi, theta, psi — Euler 角 (弧度)，不传则随机生成
% 输出:
%   MOLCOORS — 旋转后的坐标

    if nargin < 2
        % 默认: 全随机 Euler 角，均匀分布于 [0, 2π]
        phi   = rand * 2 * pi;
        theta = rand * 2 * pi;
        psi   = rand * 2 * pi;
    end

    % 平移分子到质心原点
    center = mean(MOLCOORS, 1);
    relCoords = MOLCOORS - center;

    % Z-X-Z Euler 旋转矩阵: R = Rz(phi) * Rx(theta) * Rz(psi)
    Rz1 = [cos(phi),   -sin(phi),  0;
           sin(phi),    cos(phi),  0;
           0,           0,         1];

    Rx  = [1,  0,           0;
           0,  cos(theta), -sin(theta);
           0,  sin(theta),  cos(theta)];

    Rz2 = [cos(psi),   -sin(psi),  0;
           sin(psi),    cos(psi),  0;
           0,           0,         1];

    R = Rz1 * Rx * Rz2;

    % 旋转相对坐标，然后平移回原质心位置
    relCoords = relCoords * R';
    MOLCOORS = relCoords + center;
end
