function SymmetryMutation_310(Ind_No)
% SymmetryMutation_310 — PyXtal 对称性引导变异算子
%
% 算法:
%   1. 在高对称空间群 (P2₁/c, P-1, P2₁2₁2₁ 等) 生成父代
%   2. 提取分子为 P1 表示 (去对称化)
%   3. 对每个分子施加小扰动破缺对称性
%   4. 距离检查 → 输出变体
%
% 失败时自动回退到 Random_310

global POP_STRUC
global ORG_STRUC
global OFF_STRUC

homePath = ORG_STRUC.homePath;

% ---- 构建参数 ----
molNames = {};
for i = 1:length(ORG_STRUC.numMols)
    molNames{end+1} = fullfile(homePath, ['MOL_' num2str(i)]);
end
molStr = strjoin(molNames, ',');

numMolsList = {};
for i = 1:length(ORG_STRUC.numMols)
    numMolsList{end+1} = num2str(ORG_STRUC.numMols(i));
end
numMolsStr = strjoin(numMolsList, ',');

if ORG_STRUC.constLattice
    targetVol = abs(det(ORG_STRUC.lattice));
else
    targetVol = ORG_STRUC.latVolume * sum(ORG_STRUC.numMols) / sum(ORG_STRUC.numMols);
end

% 选择高对称空间群
highSymSpgs = [14, 2, 19, 33, 61, 62];  % P2₁/c, P-1, P2₁2₁2₁, Pna2₁, Pbca, Pnma
spg = highSymSpgs(ceil(rand * length(highSymSpgs)));

% ---- 调用 Python ----
pyScript = fullfile(homePath, 'FunctionFolder', 'USPEX', '310', 'pyxtal_symmetry_mutation.py');
outDir = fullfile(homePath, 'CalcFoldTemp');
if ~exist(outDir, 'dir'), mkdir(outDir); end

seed = floor(rand * 2^31);
pythonBin = '/home/feng/.local/anaconda/bin/python3';

cmd = sprintf('%s %s --mols %s --numMols %s --volume %.1f --spg %d --n-variants 1 --seed %d --outdir %s', ...
    pythonBin, pyScript, molStr, numMolsStr, targetVol, spg, seed, outDir);
[status, ~] = system(cmd);

if status ~= 0
    Random_310(Ind_No);
    return;
end

% ---- 读取变体 ----
varDir = fullfile(outDir, 'variant_000');
if ~exist(varDir, 'dir')
    Random_310(Ind_No);
    return;
end

% 复制输出文件到工作目录
copyfile(fullfile(varDir, 'POSCAR'), fullfile(homePath, 'POSCAR'));
copyfile(fullfile(varDir, 'optimized.structure'), fullfile(homePath, 'optimized.structure'));
copyfile(fullfile(varDir, 'output'), fullfile(homePath, 'output'));

% ---- 读取分子数据 ----
dataFile = fullfile(varDir, 'molecules.txt');
if ~exist(dataFile, 'file')
    Random_310(Ind_No);
    return;
end

fid = fopen(dataFile, 'r');
header = fscanf(fid, '%d %d', 2);
nMols = header(1);

lattice = zeros(3, 3);
for i = 1:3
    lattice(i, :) = fscanf(fid, '%f %f %f', 3);
end

[typesAList, MtypeLIST, numIons] = GetPOP_MOL(ORG_STRUC.numMols);
Molecules = struct('MOLCOORS', {}, 'ZMATRIX', {}, 'ID', {}, 'MOLCENTER', {});

for i = 1:nMols
    info = fscanf(fid, '%d %d', 2);
    nAtoms = info(1);
    coords = zeros(nAtoms, 3);
    for j = 1:nAtoms
        coords(j, :) = fscanf(fid, '%f %f %f', 3);
    end
    Molecules(i).MOLCOORS = coords;
    Molecules(i).MOLCENTER = mean(coords, 1);
    format = ORG_STRUC.STDMOL(MtypeLIST(i)).format;
    Molecules(i).ZMATRIX = NEW_coord2Zmatrix(coords, format);
end
fclose(fid);

% ---- 填充 OFF_STRUC ----
OFF_STRUC.POPULATION(Ind_No).LATTICE = lattice;
OFF_STRUC.POPULATION(Ind_No).MOLECULES = Molecules;
OFF_STRUC.POPULATION(Ind_No).numIons = numIons;
OFF_STRUC.POPULATION(Ind_No).numMols = ORG_STRUC.numMols;
OFF_STRUC.POPULATION(Ind_No).MtypeLIST = MtypeLIST;
OFF_STRUC.POPULATION(Ind_No).typesAList = typesAList;
OFF_STRUC.POPULATION(Ind_No).howCome = 'SymmetryMutation';
OFF_STRUC.POPULATION(Ind_No).Parents = [];

disp(['Structure ' num2str(Ind_No) ' generated by SymmetryMutation (parent SPG ' num2str(spg) ')']);
end
